<?php


   ?>

<table>
    <thead>
    <tr>
        <th>Verb</th>
        <th>URI</th>
        <th>Typical Method Name</th>
        <th>Route Name</th>
    </tr>
    </thead>
    <tbody>
    <tr>
        <td>GET</td>
        <td><code>/photos</code></td>
        <td><code>index()</code></td>
        <td>photos.index</td>
    </tr>
    <tr>
        <td>GET</td>
        <td><code>/photos/create</code></td>
        <td><code>create()</code></td>
        <td>photos.create</td>
    </tr>
    <tr>
        <td>POST</td>
        <td><code>/photos</code></td>
        <td><code>store()</code></td>
        <td>photos.store</td>
    </tr>
    <tr>
        <td>GET</td>
        <td><code>/photos/{photo}</code></td>
        <td><code>show()</code></td>
        <td>photos.show</td>
    </tr>
    <tr>
        <td>GET</td>
        <td><code>/photos/{photo}/edit</code></td>
        <td><code>edit()</code></td>
        <td>photos.edit</td>
    </tr>
    <tr>
        <td>PUT/PATCH</td>
        <td><code>/photos/{photo}</code></td>
        <td><code>update()</code></td>
        <td>photos.update</td>
    </tr>
    <tr>
        <td>DELETE</td>
        <td><code>/photos/{photo}</code></td>
        <td><code>destroy()</code></td>
        <td>photos.destroy</td>
    </tr>
    </tbody>
</table>
